From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
From python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY attendance_app.py /home/myapp/
EXPOSE 5000
CMD python /home/myapp/attendance_app.py
